W7D2/musicapp/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
    
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: :new do  
    resources :tracks, only: :new
  end

  resources :tracks, except: :new  do 
    resources :notes, only: :create
    
  end

  resources :notes, except: :create
end

W7D2/musicapp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, presence:true

  belongs_to :band  
  def studio
    !self.live
  end

  has_many :tracks
end

W7D2/musicapp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, null:false

  has_many :albums
end

W7D2/musicapp/app/models/note.rb
class Note < ApplicationRecord
    validates :body, presence:true

    belongs_to :author,
        foreign_key: :user_id,
        class_name: :User  
        
    belongs_to :track
end

W7D2/musicapp/app/models/track.rb
class Track < ApplicationRecord
    validates :title, :ord, presence: true
    validates :regular, inclusion: { in: [true, false], message: "Can only be true or false"}
    validates :title, uniqueness: {scope: :title}

    belongs_to :album  
    has_one :band,
        through: :album,
        source: :band

    def bonus  
        !regular
    end

    has_many :notes 

end

W7D2/musicapp/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, null:false
  validates :password, length:{minimum: 3}, allow_nil: true
  after_initialize :ensure_session_token

  attr_reader :password

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.update(session_token: generate_session_token)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil 
  end

  has_many :notes
end

W7D2/musicapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_log_in
  # def index
    
  #   @albums = Album.where(band_id: params[:band_id])
  #   # debugger
  #   render :index
  # end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit    
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)

      redirect_to album_url(@album)

    else
      falsh[:errors] = @album.errors.full_messages
      redirect_to album_url(@album)  
    end
    
  end

  def new
    @album = Album.new
    @bands = Band.all
    @album.band_id = params[:band_id]
    render :new 
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      debugger
      redirect_to album_url(@album.id)
    else
      flash[errors] = @album.errors.full_messages  
      redirect_to band_url(@album.band_id)
    end
  end

  def album_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end


end

W7D2/musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :log_in?
  

  def current_user
    @user = User.find_by(session_token: session[:session_token])
  end

  def log_in? 
    !!current_user
  end

  def log_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_log_in
    redirect_to new_session_url unless log_in?
  end
end

W7D2/musicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_log_in

  def index
    @bands = Band.all  
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show

  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      #log_in!(@user)
      redirect_to bands_url
    else   
      render json: @band.errors.full_messages
    end
  end

  def edit 
    @band = Band.find(params[:id])
    render :edit
    
  end
  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      #log_in!(@user)
      redirect_to band_url(@band)
    else   
      render json: @band.errors.full_messages
    end
  end

  def band_params
    params.require(:band).permit(:name)
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end
end

W7D2/musicapp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def destroy
        @note = Note.find_by(id:params[:id])
        if @note.user_id == current_user.id
            @note.destroy
            redirect_to track_url(@note.track_id)
        else     
            flash[:errors] = ["You can only delete your own note"]
            redirect_to track_url(@note.track_id)
        end
    end
    
    def create
        # debugger
        @note = Note.new(note_params)
        @note.track_id = params[:track_id]
        @note.user_id = current_user.id
        # debugger
        if @note.save 
            # debugger
            redirect_to track_url(params[:track_id])
        else       
            flash[:errors] = @note.errors.full_messages
        end
    end

    def note_params
        params.require(:note).permit(:body)
    end
end

W7D2/musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    #fail
    @user = User.find_by_credentials(params[:session][:email], params[:session][:password])
    #debugger
    if @user
      
      log_in!(@user)
      redirect_to user_url(@user)
    else   
      render :new 
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def session_params
    session.require
  end
end

W7D2/musicapp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :require_log_in

    # def index 
    #     @tracks = Track.where(album_id:params[:album_id])
    #     render :index
    # end

    def new 
        @track = Track.new
        @albums = Album.all
        @track.album_id = params[:album_id]
        render :new
    end

    def create
        @track = Track.new(track_params)
        # debugger
        if @track.save
            redirect_to track_url(@track)
        else  
            flash[:errors] = @track.errors.full_messages
            redirect_to album_url(@track.album_id)
        end
    end

    def show 
        @track = Track.find_by(id: params[:id])
    
        render :show
    end

    def edit 
        @track = Track.find_by(id:params[:id])
        @albums = Album.all
        render :edit
    end

    def update
        @track = Track.find_by(id:params[:id])
        if @track.update(track_params)
            redirect_to track_url(@track)
        else 
            flash[:errors] = @track.errors.full_messages
            redirect_to track_url(@track)
        end
    end

    def track_params
        params.require(:track).permit(:title, :ord, :lyrics, :album_id, :regular)
    end
end

W7D2/musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else   
      render json: @user.errors.full_messages
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W7D2/musicapp/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7D2/musicapp/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/musicapp/app/helpers/notes_helper.rb
module NotesHelper
end

W7D2/musicapp/app/helpers/tracks_helper.rb
module TracksHelper
end

W7D2/musicapp/app/views/notes/_form.html.erb
<form action="<%= track_notes_url(track) %>" method="POST">
<input type="hidden" 
name="authenticity_token"
value="<%= form_authenticity_token %>">
<textarea name="note[body]" id="" cols="30" rows="10">
write here
</textarea>
<input type="submit" value="Create Note">
</form>

W7D2/musicapp/app/views/notes/_note.html.erb
 <p> <%= note.body %></p>
 <% if note.author.id == current_user.id %>
    <form action="<%= note_url(note) %>" method="POST">
    <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete Note">
    </form>
<% end  %>

W7D2/musicapp/app/views/tracks/edit.html.erb
<form action="<%= track_url(@track) %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Title  
<input type="text" name="track[title]" value="<%= @track.title %>">
</label>
<label>ORD
<input type="text" name="track[ord]" value="<%= @track.ord %>">
</label>
<br>
<label>Album
<select name="track[album_id]">
    <% @albums.each do |album| %>
        <option value="<%= album.id %>" <%= "selected" if @track.album_id == album.id%>>      
        <%= album.title %></option>
    <% end %>
</select>
</label>
<br>
<label>Regular or Bonus
    <input type="radio" name="track[regular]" value="true" <%= "checked" if @track.regular%> >Regular
    <input type="radio" name="track[regular]" value="false"<%= "checked" if @track.bonus %>>Bonus
</label>
<br>
<label>Lyrics
<textarea name="track[lyrics]"  cols="30" rows="10"><%= @track.lyrics %></textarea>
</label>
<br>
<input type="submit" value="Update">
</form>

W7D2/musicapp/app/views/tracks/index.html.erb
<% @tracks.each do |track|%>
<a href="<%= track_url(track) %>"><%= track.title %></a>

<% end %>

W7D2/musicapp/app/views/tracks/new.html.erb
<form action="<%= tracks_url %>" method="POST">
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
<input type="hidden" name="track[album_id]" value="<%= @track.album_id %>">
<select name="track[album_id]" >
    <% @albums.each do |album| %>
        <option value="<%= album.id %>" <%= "selected" if album.id == @track.album_id  %> >
        <%= album.title %></option>        
    <% end %>
</select>
<label>Title  
<input type="text" name="track[title]" value="<%= @track.title %>">
</label>
<br>
<label>Ord 
<input type="text" name="track[ord]" value="<%= @track.ord %>">
</label>
<br>
<label>Lyrics 
<textarea name="track[lyrics]" id="" cols="30" rows="10"></textarea>
</label>
<br>
<select name="track[regular]" id="">
    <option value=true>Regular</option>
    <option value=false>Bonus</option>
</select>
<input type="submit" value="Create Track">
</form>

W7D2/musicapp/app/views/tracks/show.html.erb
<label>Title:
<%= @track.title %>
<%= link_to "Edit", edit_track_url(@track) %>
</label>
<br>
<label >ORD:
<%= @track.ord %>
</label>
<br>
<label>Lyrics:
<%= @track.lyrics %>
</label>
<br>
<label>Album:
<a href="<%= album_url(@track.album) %>"> <%= @track.album.title %> </a>
</label>
<br>
<label>Regular or Bonus:
<% if @track.regular%>
    Regular
<% else %>
    Bonus
<% end %>
</label>
<br>
<ul>
    <% @track.notes.each do |note|  %>
        <li>
        <%= render 'notes/note', note: note %>
        <%= note.author.email %>
        </li>
    <% end %>
</ul>

<%= render 'notes/form', track: @track %>

W7D2/musicapp/app/views/users/index.html.erb
<h1>Here's all the users!</h1>
<ul>
<% @users.each do |user|  %>
<li><%= user.email %></li>
<% end%>
</ul>

W7D2/musicapp/app/views/users/new.html.erb
 
<form action='<%= users_url %>' method="POST">
<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
<label>Email
    <input type='text' name='user[email]' value=''>
</label>
<br>
<label>Password
    <input type='password' name='user[password]' value=''>
</label>
<br>
<input type="submit" value="Create">
</form>

W7D2/musicapp/app/views/users/show.html.erb
<h1>Here's the Info</h1>
<%= @user.email %>
<br>
<ul>
    <% @user.notes.each do |note| %> 
    <li>
    <%= note.track.title %>
    <br>
    <%= note.body %>
    <br>
    </li>
</ul>


<% end %>