W6D5/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
    resources :cat_rental_requests, only:[:index] do
      member do
        get "deny"
      end
      member do
        get 'approve'
      end
    end
  
  end

  resources :cat_rental_requests, only:[:new, :create] 

end

W6D5/cats/app/models/cat.rb
require 'date'

class Cat < ApplicationRecord
  COLORS = ['Black', 'White', 'Brown', 'Orange', 'Blue']
  validates :birth_date, :name, :color, :sex, presence: true
  validates :sex, inclusion: { in: ['M', 'F'] }
  validates :color, inclusion: { in: Cat::COLORS }
  include ActionView::Helpers::DateHelper
  def age
    # Date.today - birth_date
    time_ago_in_words(birth_date)
  end
  has_many :cat_rental_requests,
    dependent: :destroy
end

W6D5/cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    validates :cat_id, :start_date, :end_date, :status, presence:true
    validates :status, inclusion: {in: ['PENDING', 'APPROVED', 'DENIED']}
    belongs_to :cat

    def overlapping_requests
        CatRentalRequest
            .where(cat_id: self.cat_id)
            .where("start_date <= ?", self.end_date)
            .where("end_date >= ?", self.start_date)
            .where.not(id: self.id)
    end

    def overlapping_approved_requests
        overlapping_requests
            .where(status: "APPROVED")
    end

    def does_not_overlap_approved_requests
        !overlapping_approved_requests.exists?
    end

    def overlapping_pending_requests
        overlapping_requests
            .where(status: "PENDING")
    end

    def approve!
        self.update(status: "APPROVED")
        opr = overlapping_pending_requests.each do |request|
            request.update(status:'DENIED')
        end
    
    end

    def deny!
        self.update(status: "DENIED")
    end

    def pending?
        self.status == 'PENDING'
    end
end

W6D5/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W6D5/cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def new
        @cats = Cat.all
        @cat_rental_request = CatRentalRequest.new
        render :new
    end

    def create 
     
        @cat_rental_request = CatRentalRequest.new(request_params)
        if @cat_rental_request.save
            redirect_to cat_url(request_params[:cat_id])
        else  
            render json: @cat_rental_request.errors.full_messages
        end
    end

    def index
        @cat_rental_requests = CatRentalRequest.find_by(cat_id: params[:cat_id])
        render :index

    end

    def request_params
        params.require(:cat_rental_request).permit(:id, :cat_id, :start_date, :end_date, :status)
    end

    def deny
        cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        cat_rental_request.deny!
        redirect_to cat_url(cat_rental_request.cat_id)
    end

    def approve
        cat_rental_request = CatRentalRequest.find_by(id: params[:id])
        cat_rental_request.approve!
        redirect_to cat_url(cat_rental_request.cat_id)

    end


end

W6D5/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
   # render json: @cats
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    #debugger
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

W6D5/cats/app/views/cats/_form.html.erb
<% if type == 'new' %>
  <% action_url = cats_url %>
  <h1>Create Cat !</h1> 
<% elsif type == 'edit'%>
  <% action_url = cat_url(cat) %>
  <h1>Edit Cat !</h1>
<% end %>

<form action="<%=action_url%>" method='POST'>
<% if type == 'edit'%>
  <input type="hidden" name="_method" value='PATCH'>
<% end %>
Name
<br>
<input type="text" name='cat[name]' value='<%=cat.name%>'>   
<br>
Sex
<br>
<%# <% F = (cat.sex == 'F' ? true : false) %>
<%# <% M = (cat.sex == 'M' ? true : false) %>
<input type="radio" name='cat[sex]' <%#=checked if M %> value='M'>Male<br>
<input type="radio" name='cat[sex]' <%#=checked if F %> value='F'>Female<br>
Color
<br>
<select name='cat[color]'>
  <option disabled value="">choose a color</option>
  <% cat.class::COLORS.each do |color| %>
    <option value="<%=color%>" <%#=selected if cat.color == color %>><%=color%></option>
  <% end %>
</select>
<br>
Birthday
<br>
<input type="date" name='cat[birth_date]' value='<%=cat.birth_date%>'>
<br>
Description
<br>
<textarea name="cat[description]" value='<%=cat.description%>' cols="30" rows="10"></textarea>
<input type="submit" value="Update">
</form>

W6D5/cats/app/views/cats/edit.html.erb
<!-- <h1>Edit Cat !</h1>
<form action="<%=cat_url(@cat)%>" method='POST'>
<input type="hidden" name="_method" value='PATCH'>
Name
<br>
<input type="text" name='cat[name]' value='<%=@cat.name%>'>   
<br>
Sex
<br>
<%# <% F = (@cat.sex == 'F' ? true : false) %>
<%# <% M = (@cat.sex == 'M' ? true : false) %>
<input type="radio" name='cat[sex]' <%#=checked if M %> value='M'>Male<br>
<input type="radio" name='cat[sex]' <%#=checked if F %> value='F'>Female<br>
Color
<br>
<select name='cat[color]'>
  <option disabled value="">choose a color</option>
  <% @cat.class::COLORS.each do |color| %>
    <option value="<%=color%>" <%#=selected if @cat.color == color %>><%=color%></option>
  <% end %>
</select>
<br>
Birthday
<br>
<input type="date" name='cat[birth_date]' value='<%=@cat.birth_date%>'>
<br>
Description
<br>
<textarea name="cat[description]" cols="30" rows="10"></textarea>
<input type="submit" value="Update">
</form> -->

<%= render 'form', cat: @cat, type:'edit' %>

W6D5/cats/app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat| %>
      <li>
        <ol>
          <li><%= cat.name %></li>
          <li><%= cat.birth_date %></li>
          <li><%= cat.color %></li>
          <li><%= cat.sex %></li>
          <li><a href="<%= cat_url(cat) %>"> Show <%= cat.name %></a></li>
        </ol>
      </li>
    <% end %> 
</ul>

W6D5/cats/app/views/cats/new.html.erb
<!-- <h1>Create a New Cat !</h1>
<form action="<%=cats_url%>" method='POST'>
Name
<br>
<input type="text" name='cat[name]' value='<%=@cat.name%>'>   
<br>
Sex
<br>
<input type="radio" name='cat[sex]' value='M'>Male<br>
<input type="radio" name='cat[sex]' value='F'>Female<br>
Color
<br>
<select name='cat[color]'>
  <option disabled value="">choose a color</option>
  <% @cat.class::COLORS.each do |color| %>
    <option value="<%=color%>"><%=color%></option>
  <% end %>
</select>
<br>
Birthday
<br>
<input type="date" name='cat[birth_date]' value='<%=@cat.birth_date%>'>
<br>
Description
<br>
<textarea name="cat[description]" cols="30" rows="10"></textarea>
<input type="submit" value="Create">
</form> -->

<%= render 'form', cat: @cat, type:'new' %>

W6D5/cats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name %></th>  
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Attributes</td>
            <td>Value</td>            
        </tr>
        <tr>
            <td>Birthday</td>
            <td><%= @cat.birth_date %></td>            
        </tr>
        <tr>
            <td>Age</td>
            <td><%= @cat.age%></td>            
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>            
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>            
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan="2">Rental Requests</th>  
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>START DATE</td>    
            <td>END DATE</td>   
            <td>STATUS</td>           
        </tr>
        <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
            <tr>
                <td><%= request.start_date %></td>  
                <td><%= request.end_date %></td>            
                <td><%= request.status %></td>            
                <% if request.pending? %>
                    <td><a href="<%=deny_cat_cat_rental_request_url(id: request.id, cat_id: request.cat_id) %>" value='DENIED'>DENY</a></td>
                    <td><a href="<%=approve_cat_cat_rental_request_url(id: request.id, cat_id: request.cat_id) %>" value='APPROVED'>APPROVE</a></td>

                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<a href="<%=new_cat_rental_request_url%>">New Rental Request</a>