W8D1/reddit/config/routes.rb
Rails.application.routes.draw do 


 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users do

  resources :subs, only: :new
  resources :posts, only: :new
end

resource :session

resources :subs, except: :new

resources :posts, except: [:index, :new] do  
  resources :comments, only: :new
end

resources :comments, except: :new

end

W8D1/reddit/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true 
  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    dependent: :destroy
    # inverse_of: :sub 

  has_many :posts,
    through: :post_subs,
    source: :post
end

W8D1/reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
  end
  def new
    @sub = Sub.new
    @sub.user_id = params[:user_id]
    render :new
  end

  def create
    @sub = Sub.create!(sub_params)
    if @sub 
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.user_id == current_user.id 
      if @sub.update_attributes(sub_params)
        redirect_to sub_url(@sub)
      else 
        flash[:errors] = @sub.errors.full_messages
        render :edit
      end
    else
      flash[:errors] = ["Only moderator can edit a sub"]
      redirect_to sub_url 
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :user_id)
  end
  
end

W8D1/reddit/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

<form action="<%= sub_url %>" method='POST'>
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Title:
<input type="text" name="sub[title]" value="<%= @sub.title %>">
</label>

<label>Description
<input type="text" name="sub[description]" value="<%= @sub.description %>">
</label>


<button>Update Sub</button>
</form>

W8D1/reddit/app/views/subs/index.html.erb
All the Subs
<% @subs.each do |sub| %>
<%= link_to sub.title, sub_url(sub) %>
<br>
<% end %>

W8D1/reddit/app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>


<form action="<%= subs_url %>" method='POST'>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Title:
<input type="text" name="sub[title]">
</label>

<label>Description
<input type="text" name="sub[description]">
</label>
 

 <input type="hidden" name="sub[user_id]" value="<%= @sub.user_id %>">

<button>Create Sub</button>
</form>

W8D1/reddit/app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>


<label>Title:
  <%= @sub.title %>
  <%= link_to "edit", edit_sub_url(@sub) %>
</label>
<br>
<label>Description:
  <%= @sub.description %>
</label>
<br>
<label>Moderator:
  <%= @sub.moderator.username %>
</label>

<label>Posts
  <% @sub.posts.each do |post| %>
  <%= link_to "#{post.title}", post_url(post) %>
  <br>
  <% end %>
</label>