W8D1/reddit/config/routes.rb
Rails.application.routes.draw do 


 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users do

  resources :subs, only: :new
  resources :posts, only: :new
end

resource :session

resources :subs, except: :new

resources :posts, except: [:index, :new] do  
  resources :comments, only: :new
end

resources :comments, except: :new

end

W8D1/reddit/app/models/user.rb
class User < ApplicationRecord

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true 
  validates :password, length: {minimum: 6, allow_nil: true} 


  attr_reader :password 

  after_initialize :ensure_session_token

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token 
    self.session_token ||= SecureRandom.base64
  end

  def reset_session_token!
    self.update(session_token:SecureRandom.base64)
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = self.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end


  has_many :subs
  has_many :posts
  has_many :comments 

end

W8D1/reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: :show
  def new
    @user = User.new 
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new 
    end

  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

W8D1/reddit/app/helpers/users_helper.rb
module UsersHelper
end

W8D1/reddit/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

W8D1/reddit/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Username:
<input type="text" name="user[username]" value="<%= @user.username %>">
</label>
<label>Password:
<input type="password" name="user[password]" value="">
<BUtton>Sign Up</BUtton>

</form>

W8D1/reddit/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= @user.username %>
<br>
<%= link_to "create new sub", new_user_sub_url(@user) %>
<br>
<%= link_to "create new post", new_user_post_url(@user) %>
<br>
My subs:
<br>
<% @user.subs.each do |sub|%>

  <a href="<%= sub_url(sub) %>"> <%= sub.title %></a>
  <br>
<% end %>
<br>
My posts:
<br>
<% @user.posts.each do |post| %>
  <%= link_to post.title, post_url(post) %>
  <br>
<%end %>